apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: vky84/weatherapi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"