apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libraryapi
  template:
    metadata:
      labels:
        app: libraryapi
    spec:
      containers:
      - name: libraryapi
        image: vky84/libraryapi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"