apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libraryapi
  template:
    metadata:
      labels:
        app: libraryapi
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z postgres 5432; do
              echo "Waiting for Postgres..."
              sleep 2
            done
      containers:
      - name: libraryapi
        image: vky84/libraryapi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__Default
          value: 'Host=postgres;Port=5432;Database=LibraryDb;Username=postgres;Password=postgres'
