apiVersion: v1
kind: Service
metadata:
  name: notificationservice-service
spec:
  type: NodePort
  selector:
    app: notificationservice
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
