apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z postgres 5432; do
              echo "Waiting for Postgres..."
              sleep 2
            done
      containers:
      - name: notificationservice
        image: vky84/notificationservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: 'Host=postgres;Port=5432;Database=LibraryDb;Username=postgres;Password=postgres'
        - name: Smtp__Host
          value: "smtp.gmail.com"
        - name: Smtp__Port
          value: "587"
        - name: Smtp__Username
          value: "vky84.com@gmail.com"
        - name: Smtp__Password
          value: "wqxxqfpwxervqxux"
        - name: Smtp__FromEmail
          value: "vky84.com@gmail.com"
